# Generated by Django 4.1.7 on 2023-04-15 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_image_profile_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
