import React from 'react'

const MainBody = () => {
  return (
    <div className='border-x-2 border-gray-300'>Here's some randomly generated text with 10,000 words:

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at leo at elit sollicitudin convallis. Duis imperdiet laoreet commodo. Quisque ultrices ligula eget purus facilisis ullamcorper. Nullam consectetur dapibus lectus, vel iaculis metus. Proin id enim id massa congue consequat. Integer tempor massa vitae eros commodo, at lacinia libero vestibulum. Sed ut sodales justo. Nulla vel luctus urna. Sed eget lectus vel nisi lacinia facilisis id eu nunc. Nullam quis risus ac magna malesuada elementum. Aliquam iaculis, mi a consectetur tincidunt, dolor mauris mollis sapien, sed venenatis magna dolor in sapien. Fusce lacinia quam et odio facilisis, at molestie ante ultrices. Vivamus sit amet neque vel tellus pharetra posuere. Nullam condimentum, metus quis facilisis mollis, turpis eros commodo ex, non hendrerit nibh dolor vitae nunc.
    
    Phasellus nec elit lectus. Suspendisse potenti. Sed lobortis, velit eget dapibus suscipit, sapien mauris tristique lectus, sed pulvinar felis nisi sed mi. Sed pharetra lacus et nibh aliquet elementum. Donec id dolor ut enim dignissim iaculis ut vitae mauris. Fusce luctus feugiat metus, ut euismod elit tristique vitae. Donec bibendum diam enim, quis facilisis dolor pellentesque nec. In hac habitasse platea dictumst. Sed rhoncus odio a augue blandit, nec vestibulum sapien pretium. Praesent ac tincidunt sapien. Fusce euismod urna vel massa tincidunt sagittis. Sed sed lorem vel est vulputate eleifend a sit amet odio.
    
    Integer sollicitudin fermentum velit, vel vulputate mauris. Sed eget eros quis quam pharetra vestibulum ac vel metus. Nunc quis neque metus. Pellentesque sagittis, enim sed imperdiet pretium, turpis nisl lacinia magna, sit amet laoreet mi magna eget metus. Donec tempor dui vel turpis malesuada, ac luctus ante pretium. Nunc ac elit quis elit lobortis molestie ut at tellus. Duis fringilla auctor faucibus. Morbi eget augue tortor. Aliquam bibendum mauris ut ex luctus, at laoreet eros faucibus. Donec non feugiat mi. Pellentesque semper ullamcorper enim, vel bibendum quam molestie at. Suspendisse sit amet risus non mi tempor feugiat eu non sem.
    
    Suspendisse bibendum augue non sapien rutrum lacinia. Vivamus vel dui id enim fringilla tempor ac id dui. Curabitur interdum ultrices felis sit amet semper. Vivamus tincidunt dignissim justo. Sed finibus efficitur leo, vel viverra turpis tristique in. Fusce dignissim ligula nec gravida hendrerit. Sed feugiat ante a velit dapibus interdum. Sed rhoncus faucibus mi, at volutpat odio consequat eget. Vivamus finibus augue vel ipsum bibendum ultrices. Duis eget tincidunt dolor. Sed id mollis nibh. Suspendisse interdum Here's some randomly generated text with 10,000 words:

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at leo at elit sollicitudin convallis. Duis imperdiet laoreet commodo. Quisque ultrices ligula eget purus facilisis ullamcorper. Nullam consectetur dapibus lectus, vel iaculis metus. Proin id enim id massa congue consequat. Integer tempor massa vitae eros commodo, at lacinia libero vestibulum. Sed ut sodales justo. Nulla vel luctus urna. Sed eget lectus vel nisi lacinia facilisis id eu nunc. Nullam quis risus ac magna malesuada elementum. Aliquam iaculis, mi a consectetur tincidunt, dolor mauris mollis sapien, sed venenatis magna dolor in sapien. Fusce lacinia quam et odio facilisis, at molestie ante ultrices. Vivamus sit amet neque vel tellus pharetra posuere. Nullam condimentum, metus quis facilisis mollis, turpis eros commodo ex, non hendrerit nibh dolor vitae nunc.

Phasellus nec elit lectus. Suspendisse potenti. Sed lobortis, velit eget dapibus suscipit, sapien mauris tristique lectus, sed pulvinar felis nisi sed mi. Sed pharetra lacus et nibh aliquet elementum. Donec id dolor ut enim dignissim iaculis ut vitae mauris. Fusce luctus feugiat metus, ut euismod elit tristique vitae. Donec bibendum diam enim, quis facilisis dolor pellentesque nec. In hac habitasse platea dictumst. Sed rhoncus odio a augue blandit, nec vestibulum sapien pretium. Praesent ac tincidunt sapien. Fusce euismod urna vel massa tincidunt sagittis. Sed sed lorem vel est vulputate eleifend a sit amet odio.

Integer sollicitudin fermentum velit, vel vulputate mauris. Sed eget eros quis quam pharetra vestibulum ac vel metus. Nunc quis neque metus. Pellentesque sagittis, enim sed imperdiet pretium, turpis nisl lacinia magna, sit amet laoreet mi magna eget metus. Donec tempor dui vel turpis malesuada, ac luctus ante pretium. Nunc ac elit quis elit lobortis molestie ut at tellus. Duis fringilla auctor faucibus. Morbi eget augue tortor. Aliquam bibendum mauris ut ex luctus, at laoreet eros faucibus. Donec non feugiat mi. Pellentesque semper ullamcorper enim, vel bibendum quam molestie at. Suspendisse sit amet risus non mi tempor feugiat eu non sem.

Suspendisse bibendum augue non sapien rutrum lacinia. Vivamus vel dui id enim fringilla tempor ac id dui. Curabitur interdum ultrices felis sit amet semper. Vivamus tincidunt dignissim justo. Sed finibus efficitur leo, vel viverra turpis tristique in. Fusce dignissim ligula nec gravida hendrerit. Sed feugiat ante a velit dapibus interdum. Sed rhoncus faucibus mi, at volutpat odio consequat eget. Vivamus finibus augue vel ipsum bibendum ultrices. Duis eget tincidunt dolor. Sed id mollis nibh. Suspendisse interdum bibendum mi,Here's some randomly generated text with 10,000 words:

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at leo at elit sollicitudin convallis. Duis imperdiet laoreet commodo. Quisque ultrices ligula eget purus facilisis ullamcorper. Nullam consectetur dapibus lectus, vel iaculis metus. Proin id enim id massa congue consequat. Integer tempor massa vitae eros commodo, at lacinia libero vestibulum. Sed ut sodales justo. Nulla vel luctus urna. Sed eget lectus vel nisi lacinia facilisis id eu nunc. Nullam quis risus ac magna malesuada elementum. Aliquam iaculis, mi a consectetur tincidunt, dolor mauris mollis sapien, sed venenatis magna dolor in sapien. Fusce lacinia quam et odio facilisis, at molestie ante ultrices. Vivamus sit amet neque vel tellus pharetra posuere. Nullam condimentum, metus quis facilisis mollis, turpis eros commodo ex, non hendrerit nibh dolor vitae nunc.

Phasellus nec elit lectus. Suspendisse potenti. Sed lobortis, velit eget dapibus suscipit, sapien mauris tristique lectus, sed pulvinar felis nisi sed mi. Sed pharetra lacus et nibh aliquet elementum. Donec id dolor ut enim dignissim iaculis ut vitae mauris. Fusce luctus feugiat metus, ut euismod elit tristique vitae. Donec bibendum diam enim, quis facilisis dolor pellentesque nec. In hac habitasse platea dictumst. Sed rhoncus odio a augue blandit, nec vestibulum sapien pretium. Praesent ac tincidunt sapien. Fusce euismod urna vel massa tincidunt sagittis. Sed sed lorem vel est vulputate eleifend a sit amet odio.

Integer sollicitudin fermentum velit, vel vulputate mauris. Sed eget eros quis quam pharetra vestibulum ac vel metus. Nunc quis neque metus. Pellentesque sagittis, enim sed imperdiet pretium, turpis nisl lacinia magna, sit amet laoreet mi magna eget metus. Donec tempor dui vel turpis malesuada, ac luctus ante pretium. Nunc ac elit quis elit lobortis molestie ut at tellus. Duis fringilla auctor faucibus. Morbi eget augue tortor. Aliquam bibendum mauris ut ex luctus, at laoreet eros faucibus. Donec non feugiat mi. Pellentesque semper ullamcorper enim, vel bibendum quam molestie at. Suspendisse sit amet risus non mi tempor feugiat eu non sem.

Suspendisse bibendum augue non sapien rutrum lacinia. Vivamus vel dui id enim fringilla tempor ac id dui. Curabitur interdum ultrices felis sit amet semper. Vivamus tincidunt dignissim justo. Sed finibus efficitur leo, vel viverra turpis tristique in. Fusce dignissim ligula nec gravida hendrerit. Sed feugiat ante a velit dapibus interdum. Sed rhoncus faucibus mi, at volutpat odio consequat eget. Vivamus finibus augue vel ipsum bibendum ultrices. Duis eget tincidunt dolor. Sed id mollis nibh. Suspendisse interdum bibendum mi,Here's some randomly generated text with 10,000 words:

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at leo at elit sollicitudin convallis. Duis imperdiet laoreet commodo. Quisque ultrices ligula eget purus facilisis ullamcorper. Nullam consectetur dapibus lectus, vel iaculis metus. Proin id enim id massa congue consequat. Integer tempor massa vitae eros commodo, at lacinia libero vestibulum. Sed ut sodales justo. Nulla vel luctus urna. Sed eget lectus vel nisi lacinia facilisis id eu nunc. Nullam quis risus ac magna malesuada elementum. Aliquam iaculis, mi a consectetur tincidunt, dolor mauris mollis sapien, sed venenatis magna dolor in sapien. Fusce lacinia quam et odio facilisis, at molestie ante ultrices. Vivamus sit amet neque vel tellus pharetra posuere. Nullam condimentum, metus quis facilisis mollis, turpis eros commodo ex, non hendrerit nibh dolor vitae nunc.

Phasellus nec elit lectus. Suspendisse potenti. Sed lobortis, velit eget dapibus suscipit, sapien mauris tristique lectus, sed pulvinar felis nisi sed mi. Sed pharetra lacus et nibh aliquet elementum. Donec id dolor ut enim dignissim iaculis ut vitae mauris. Fusce luctus feugiat metus, ut euismod elit tristique vitae. Donec bibendum diam enim, quis facilisis dolor pellentesque nec. In hac habitasse platea dictumst. Sed rhoncus odio a augue blandit, nec vestibulum sapien pretium. Praesent ac tincidunt sapien. Fusce euismod urna vel massa tincidunt sagittis. Sed sed lorem vel est vulputate eleifend a sit amet odio.

Integer sollicitudin fermentum velit, vel vulputate mauris. Sed eget eros quis quam pharetra vestibulum ac vel metus. Nunc quis neque metus. Pellentesque sagittis, enim sed imperdiet pretium, turpis nisl lacinia magna, sit amet laoreet mi magna eget metus. Donec tempor dui vel turpis malesuada, ac luctus ante pretium. Nunc ac elit quis elit lobortis molestie ut at tellus. Duis fringilla auctor faucibus. Morbi eget augue tortor. Aliquam bibendum mauris ut ex luctus, at laoreet eros faucibus. Donec non feugiat mi. Pellentesque semper ullamcorper enim, vel bibendum quam molestie at. Suspendisse sit amet risus non mi tempor feugiat eu non sem.

Suspendisse bibendum augue non sapien rutrum lacinia. Vivamus vel dui id enim fringilla tempor ac id dui. Curabitur interdum ultrices felis sit amet semper. Vivamus tincidunt dignissim justo. Sed finibus efficitur leo, vel viverra turpis tristique in. Fusce dignissim ligula nec gravida hendrerit. Sed feugiat ante a velit dapibus interdum. Sed rhoncus faucibus mi, at volutpat odio consequat eget. Vivamus finibus augue vel ipsum bibendum ultrices. Duis eget tincidunt dolor. Sed id mollis nibh. Suspendisse interdum bibendum mi,Here's some randomly generated text with 10,000 words:

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at leo at elit sollicitudin convallis. Duis imperdiet laoreet commodo. Quisque ultrices ligula eget purus facilisis ullamcorper. Nullam consectetur dapibus lectus, vel iaculis metus. Proin id enim id massa congue consequat. Integer tempor massa vitae eros commodo, at lacinia libero vestibulum. Sed ut sodales justo. Nulla vel luctus urna. Sed eget lectus vel nisi lacinia facilisis id eu nunc. Nullam quis risus ac magna malesuada elementum. Aliquam iaculis, mi a consectetur tincidunt, dolor mauris mollis sapien, sed venenatis magna dolor in sapien. Fusce lacinia quam et odio facilisis, at molestie ante ultrices. Vivamus sit amet neque vel tellus pharetra posuere. Nullam condimentum, metus quis facilisis mollis, turpis eros commodo ex, non hendrerit nibh dolor vitae nunc.

Phasellus nec elit lectus. Suspendisse potenti. Sed lobortis, velit eget dapibus suscipit, sapien mauris tristique lectus, sed pulvinar felis nisi sed mi. Sed pharetra lacus et nibh aliquet elementum. Donec id dolor ut enim dignissim iaculis ut vitae mauris. Fusce luctus feugiat metus, ut euismod elit tristique vitae. Donec bibendum diam enim, quis facilisis dolor pellentesque nec. In hac habitasse platea dictumst. Sed rhoncus odio a augue blandit, nec vestibulum sapien pretium. Praesent ac tincidunt sapien. Fusce euismod urna vel massa tincidunt sagittis. Sed sed lorem vel est vulputate eleifend a sit amet odio.

Integer sollicitudin fermentum velit, vel vulputate mauris. Sed eget eros quis quam pharetra vestibulum ac vel metus. Nunc quis neque metus. Pellentesque sagittis, enim sed imperdiet pretium, turpis nisl lacinia magna, sit amet laoreet mi magna eget metus. Donec tempor dui vel turpis malesuada, ac luctus ante pretium. Nunc ac elit quis elit lobortis molestie ut at tellus. Duis fringilla auctor faucibus. Morbi eget augue tortor. Aliquam bibendum mauris ut ex luctus, at laoreet eros faucibus. Donec non feugiat mi. Pellentesque semper ullamcorper enim, vel bibendum quam molestie at. Suspendisse sit amet risus non mi tempor feugiat eu non sem.

Suspendisse bibendum augue non sapien rutrum lacinia. Vivamus vel dui id enim fringilla tempor ac id dui. Curabitur interdum ultrices felis sit amet semper. Vivamus tincidunt dignissim justo. Sed finibus efficitur leo, vel viverra turpis tristique in. Fusce dignissim ligula nec gravida hendrerit. Sed feugiat ante a velit dapibus interdum. Sed rhoncus faucibus mi, at volutpat odio consequat eget. Vivamus finibus augue vel ipsum bibendum ultrices. Duis eget tincidunt dolor. Sed id mollis nibh. Suspendisse interdum bibendum mi,Here's some randomly generated text with 10,000 words:

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at leo at elit sollicitudin convallis. Duis imperdiet laoreet commodo. Quisque ultrices ligula eget purus facilisis ullamcorper. Nullam consectetur dapibus lectus, vel iaculis metus. Proin id enim id massa congue consequat. Integer tempor massa vitae eros commodo, at lacinia libero vestibulum. Sed ut sodales justo. Nulla vel luctus urna. Sed eget lectus vel nisi lacinia facilisis id eu nunc. Nullam quis risus ac magna malesuada elementum. Aliquam iaculis, mi a consectetur tincidunt, dolor mauris mollis sapien, sed venenatis magna dolor in sapien. Fusce lacinia quam et odio facilisis, at molestie ante ultrices. Vivamus sit amet neque vel tellus pharetra posuere. Nullam condimentum, metus quis facilisis mollis, turpis eros commodo ex, non hendrerit nibh dolor vitae nunc.

Phasellus nec elit lectus. Suspendisse potenti. Sed lobortis, velit eget dapibus suscipit, sapien mauris tristique lectus, sed pulvinar felis nisi sed mi. Sed pharetra lacus et nibh aliquet elementum. Donec id dolor ut enim dignissim iaculis ut vitae mauris. Fusce luctus feugiat metus, ut euismod elit tristique vitae. Donec bibendum diam enim, quis facilisis dolor pellentesque nec. In hac habitasse platea dictumst. Sed rhoncus odio a augue blandit, nec vestibulum sapien pretium. Praesent ac tincidunt sapien. Fusce euismod urna vel massa tincidunt sagittis. Sed sed lorem vel est vulputate eleifend a sit amet odio.

Integer sollicitudin fermentum velit, vel vulputate mauris. Sed eget eros quis quam pharetra vestibulum ac vel metus. Nunc quis neque metus. Pellentesque sagittis, enim sed imperdiet pretium, turpis nisl lacinia magna, sit amet laoreet mi magna eget metus. Donec tempor dui vel turpis malesuada, ac luctus ante pretium. Nunc ac elit quis elit lobortis molestie ut at tellus. Duis fringilla auctor faucibus. Morbi eget augue tortor. Aliquam bibendum mauris ut ex luctus, at laoreet eros faucibus. Donec non feugiat mi. Pellentesque semper ullamcorper enim, vel bibendum quam molestie at. Suspendisse sit amet risus non mi tempor feugiat eu non sem.

Suspendisse bibendum augue non sapien rutrum lacinia. Vivamus vel dui id enim fringilla tempor ac id dui. Curabitur interdum ultrices felis sit amet semper. Vivamus tincidunt dignissim justo. Sed finibus efficitur leo, vel viverra turpis tristique in. Fusce dignissim ligula nec gravida hendrerit. Sed feugiat ante a velit dapibus interdum. Sed rhoncus faucibus mi, at volutpat odio consequat eget. Vivamus finibus augue vel ipsum bibendum ultrices. Duis eget tincidunt dolor. Sed id mollis nibh. Suspendisse interdum bibendum mi,Here's some randomly generated text with 10,000 words:

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at leo at elit sollicitudin convallis. Duis imperdiet laoreet commodo. Quisque ultrices ligula eget purus facilisis ullamcorper. Nullam consectetur dapibus lectus, vel iaculis metus. Proin id enim id massa congue consequat. Integer tempor massa vitae eros commodo, at lacinia libero vestibulum. Sed ut sodales justo. Nulla vel luctus urna. Sed eget lectus vel nisi lacinia facilisis id eu nunc. Nullam quis risus ac magna malesuada elementum. Aliquam iaculis, mi a consectetur tincidunt, dolor mauris mollis sapien, sed venenatis magna dolor in sapien. Fusce lacinia quam et odio facilisis, at molestie ante ultrices. Vivamus sit amet neque vel tellus pharetra posuere. Nullam condimentum, metus quis facilisis mollis, turpis eros commodo ex, non hendrerit nibh dolor vitae nunc.

Phasellus nec elit lectus. Suspendisse potenti. Sed lobortis, velit eget dapibus suscipit, sapien mauris tristique lectus, sed pulvinar felis nisi sed mi. Sed pharetra lacus et nibh aliquet elementum. Donec id dolor ut enim dignissim iaculis ut vitae mauris. Fusce luctus feugiat metus, ut euismod elit tristique vitae. Donec bibendum diam enim, quis facilisis dolor pellentesque nec. In hac habitasse platea dictumst. Sed rhoncus odio a augue blandit, nec vestibulum sapien pretium. Praesent ac tincidunt sapien. Fusce euismod urna vel massa tincidunt sagittis. Sed sed lorem vel est vulputate eleifend a sit amet odio.

Integer sollicitudin fermentum velit, vel vulputate mauris. Sed eget eros quis quam pharetra vestibulum ac vel metus. Nunc quis neque metus. Pellentesque sagittis, enim sed imperdiet pretium, turpis nisl lacinia magna, sit amet laoreet mi magna eget metus. Donec tempor dui vel turpis malesuada, ac luctus ante pretium. Nunc ac elit quis elit lobortis molestie ut at tellus. Duis fringilla auctor faucibus. Morbi eget augue tortor. Aliquam bibendum mauris ut ex luctus, at laoreet eros faucibus. Donec non feugiat mi. Pellentesque semper ullamcorper enim, vel bibendum quam molestie at. Suspendisse sit amet risus non mi tempor feugiat eu non sem.

Suspendisse bibendum augue non sapien rutrum lacinia. Vivamus vel dui id enim fringilla tempor ac id dui. Curabitur interdum ultrices felis sit amet semper. Vivamus tincidunt dignissim justo. Sed finibus efficitur leo, vel viverra turpis tristique in. Fusce dignissim ligula nec gravida hendrerit. Sed feugiat ante a velit dapibus interdum. Sed rhoncus faucibus mi, at volutpat odio consequat eget. Vivamus finibus augue vel ipsum bibendum ultrices. Duis eget tincidunt dolor. Sed id mollis nibh. Suspendisse interdum bibendum mi,bibendum mi,</div>
  )
}

export default MainBody